# Generated by Django 4.2.5 on 2023-09-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, verbose_name=True)),
                ('joined_date', models.DateField(null=True)),
                ('bit_character', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('tasks', models.URLField(null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'NO POVERTY'), ('2', 'ZERO HUNGER'), ('3', 'GOOD HEALTH AND WELL-BEING'), ('4', 'QUALITY EDUCATION'), ('5', 'GENDER EQUALITY'), ('6', 'CLEAN WATER AND SANITATION'), ('7', 'AFFORDABLE AND CLEAN ENERGY'), ('8', 'DECENT WORK AND ECONOMIC GROWTH'), ('9', 'INDUSTRY, INNOVATION AND INFRASTRUCTURE'), ('10', 'REDUCED INEQUALITIES'), ('11', 'SUATAINABLE CITIES AND COMMUNITIES'), ('12', 'RESPONSIBLE CONSUMPTION AND PRODUCTION'), ('13', 'CLIMATE ACTION'), ('14', 'LIFE BELOW WATER'), ('15', 'LIFE ON LAND'), ('16', 'PEACE, JUSTICE AND STRONG INSTITUTIONS'), ('17', 'PARTNERSHIPS FOR THE GOALS')], default='1', max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('country', models.CharField(max_length=255)),
                ('map', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
