# Generated by Django 4.2.5 on 2023-09-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='TASK', max_length=255),
        ),
        migrations.AlterField(
            model_name='hero',
            name='bit_character',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
