# Generated by Django 4.2.5 on 2023-09-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_post_name_alter_hero_bit_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'NO POVERTY'), ('2', 'ZERO HUNGER'), ('3', 'GOOD HEALTH AND WELL-BEING'), ('4', 'QUALITY EDUCATION'), ('5', 'GENDER EQUALITY'), ('6', 'CLEAN WATER AND SANITATION'), ('7', 'AFFORDABLE AND CLEAN ENERGY'), ('8', 'DECENT WORK AND ECONOMIC GROWTH'), ('9', 'INDUSTRY, INNOVATION AND INFRASTRUCTURE'), ('10', 'REDUCED INEQUALITIES'), ('11', 'SUSTAINABLE CITIES AND COMMUNITIES'), ('12', 'RESPONSIBLE CONSUMPTION AND PRODUCTION'), ('13', 'CLIMATE ACTION'), ('14', 'LIFE BELOW WATER'), ('15', 'LIFE ON LAND'), ('16', 'PEACE, JUSTICE AND STRONG INSTITUTIONS'), ('17', 'PARTNERSHIPS FOR THE GOALS')], default='1', max_length=20),
        ),
    ]
