# Generated by Django 4.2.5 on 2023-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_post_image_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='updates/')),
            ],
        ),
    ]
