# Generated by Django 4.2.5 on 2023-09-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
    ]
