# Generated by Django 3.1.2 on 2023-10-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SDGs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
