# Generated by Django 3.1.2 on 2023-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDGs', '0002_auto_20231028_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='images',
        ),
        migrations.AddField(
            model_name='goal',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
