# Generated by Django 3.1.2 on 2023-10-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDGs', '0003_auto_20231028_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='goal',
            name='content2',
            field=models.TextField(null=True),
        ),
    ]
