# Generated by Django 3.1.2 on 2023-10-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDGs', '0004_auto_20231028_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
